/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/my-module.module';
import * as import2 from '@angular/core/src/di/injector';
class MyModuleInjector extends import0.NgModuleInjector<import1.MyModule> {
  _MyModule_0:import1.MyModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.MyModule {
    this._MyModule_0 = new import1.MyModule();
    return this._MyModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.MyModule)) { return this._MyModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MyModuleNgFactory:import0.NgModuleFactory<import1.MyModule> = new import0.NgModuleFactory(MyModuleInjector,import1.MyModule);