/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/my-module.module';
export const MyModuleNgFactory:i0.NgModuleFactory<i1.MyModule> = i0.ɵcmf(i1.MyModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.MyModule,i1.MyModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWVnZ2llL0RvY3VtZW50cy9Lcm9ub0dyb3VwL2FuZ3VsYXIyLWFwaS1rcm9uby9zcmMvbXktbW9kdWxlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21lZ2dpZS9Eb2N1bWVudHMvS3Jvbm9Hcm91cC9hbmd1bGFyMi1hcGkta3Jvbm8vc3JjL215LW1vZHVsZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzsifQ==
