/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/components/my-component';
const styles_MyComponent:any[] = ([] as any[]);
export const RenderType_MyComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_MyComponent,
    data:{}});
export function View_MyComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['I\'m a special snowflake']))],(null as any),(null as any));
}
export function View_MyComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_MyComponent_0,RenderType_MyComponent)),
      i0.ɵdid(1,49152,(null as any),0,i1.MyComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const MyComponentNgFactory:i0.ComponentFactory<i1.MyComponent> = i0.ɵccf('my-component',
    i1.MyComponent,View_MyComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWVnZ2llL0RvY3VtZW50cy9Lcm9ub0dyb3VwL2FuZ3VsYXIyLWFwaS1rcm9uby9zcmMvY29tcG9uZW50cy9teS1jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tZWdnaWUvRG9jdW1lbnRzL0tyb25vR3JvdXAvYW5ndWxhcjItYXBpLWtyb25vL3NyYy9jb21wb25lbnRzL215LWNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvbWVnZ2llL0RvY3VtZW50cy9Lcm9ub0dyb3VwL2FuZ3VsYXIyLWFwaS1rcm9uby9zcmMvY29tcG9uZW50cy9teS1jb21wb25lbnQudHMuTXlDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvbWVnZ2llL0RvY3VtZW50cy9Lcm9ub0dyb3VwL2FuZ3VsYXIyLWFwaS1rcm9uby9zcmMvY29tcG9uZW50cy9teS1jb21wb25lbnQudHMuTXlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2PkknbSBhIHNwZWNpYWwgc25vd2ZsYWtlPC9kaXY+IiwiPG15LWNvbXBvbmVudD48L215LWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFLO2FBQUE7OztvQkNBTDtNQUFBO2FBQUE7Ozs7In0=
